# Generated by Django 3.2.14 on 2022-08-21 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_application_rsvp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='gender',
        ),
        migrations.AddField(
            model_name='application',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='devpost',
            field=models.CharField(blank=True, help_text='Devpost Link', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='first_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='github',
            field=models.CharField(blank=True, help_text='Github Link', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='last_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='linkedin',
            field=models.CharField(blank=True, help_text='LinkedIn link', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='program',
            field=models.CharField(default='', help_text='Program or Major', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='pronouns',
            field=models.CharField(choices=[(None, ''), ('he/him', 'he/him'), ('she/her', 'she/her'), ('they/them', 'they/them'), ('other', 'other'), ('no-answer', 'prefer not to answer')], default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='q1',
            field=models.TextField(help_text='Why do you want to participate in NewHacks?', max_length=1000),
        ),
        migrations.AlterField(
            model_name='application',
            name='q2',
            field=models.TextField(help_text='What is your technical experience with software?', max_length=1000),
        ),
        migrations.AlterField(
            model_name='application',
            name='q3',
            field=models.TextField(help_text='Describe any past experience with if any.', max_length=1000),
        ),
    ]
