# Generated by Django 3.2.14 on 2022-08-26 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20220826_0025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='data_agree',
        ),
        migrations.RemoveField(
            model_name='application',
            name='email',
        ),
        migrations.RemoveField(
            model_name='application',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='last_name',
        ),
        migrations.AddField(
            model_name='application',
            name='email_agree',
            field=models.BooleanField(blank=True, default='', help_text='I authorize MLH to send me pre- and post-event informational emails, which contain free credit and opportunities from their partners.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='logistics_agree',
            field=models.BooleanField(default='', help_text='I authorize you to share my application/registration information with Major League Hackingfor event administration, ranking, and MLH administration in-line with the <a href="https://mlh.io/privacy">MLH Privacy Policy</a>. I further agree to the terms of both the <a href="https://github.com/MLH/mlh-policies/tree/master/prize-terms-and-conditions">MLH Contest Terms and Conditions</a> and the <a href="https://mlh.io/privacy">MLH Privacy Policy.</a>'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='resume_sharing',
            field=models.BooleanField(blank=True, default='', help_text='I consent to IEEE UofT sharing my resume with event sponsors.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='conduct_agree',
            field=models.BooleanField(help_text='I have read and agree to the <a href="https://static.mlh.io/docs/mlh-code-of-conduct.pdf">MLH code of conduct</a>.'),
        ),
        migrations.AlterField(
            model_name='application',
            name='devpost',
            field=models.URLField(blank=True, help_text='Devpost link', null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='github',
            field=models.URLField(blank=True, help_text='Github link', null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='linkedin',
            field=models.URLField(blank=True, help_text='LinkedIn link', null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='pronouns',
            field=models.CharField(choices=[(None, ''), ('he-him', 'he/him'), ('she-her', 'she/her'), ('they-them', 'they/them'), ('other', 'other'), ('no-answer', 'prefer not to answer')], max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='q3',
            field=models.TextField(help_text='Describe any past experience if any.', max_length=1000),
        ),
    ]
