# Generated by Django 3.2.12 on 2022-09-05 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20220903_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='rsvp',
        ),
    ]
