# Generated by Django 3.2.14 on 2022-08-28 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0005_auto_20220828_1643"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="email_agree",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="I authorize MLH to send me pre- and post-event informational emails, which contain free credit and opportunities from their partners.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="resume_sharing",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="I consent to IEEE UofT sharing my resume with event sponsors.",
                null=True,
            ),
        ),
    ]
