version: '3'

services:
    postgres:
        image: postgres:12.2
        container_name: newhacks-site-2022_postgres
        ports:
            - 5432:5432
        environment:
            - POSTGRES_DB=hackathon_site
            - POSTGRES_HOST_AUTH_METHOD=trust
        volumes:
            - newhacks-site-2022_postgres-data:/var/lib/postgresql/data
    redis:
        image: redis:6-alpine
        container_name: newhacks-site-2022_redis
        ports:
            - 6379:6379

volumes:
    newhacks-site-2022_postgres-data:
